# Generated by Django 6.0.1 on 2026-03-22 16:07

import accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, help_text='Мобилен телефон за връзка (във формат 0888 123 456)', max_length=15, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, help_text='Адрес за доставка (улица, номер, град, пощенски код)', verbose_name='Адрес')),
                ('date_of_birth', models.DateField(blank=True, help_text='Моля, въведете дата на раждане (формат: ГГГГ-ММ-ДД)', null=True, verbose_name='Дата на раждане')),
                ('profile_picture', models.ImageField(blank=True, help_text='Качете профилна снимка (макс. 5MB, формати: JPG, PNG, GIF, WebP)', null=True, upload_to='profiles/%Y/%m/%d/', validators=[accounts.models.validate_image_file], verbose_name='Профилна снимка')),
                ('newsletter_subscribed', models.BooleanField(default=True, help_text='Желая да получавам имейли за нови продукти и промоции', verbose_name='Абонамент за бюлетин')),
                ('loyalty_points', models.IntegerField(default=0, help_text='Точки за лоялност, които могат да се използват за отстъпки', verbose_name='Точки за лоялност')),
                ('favourites', models.ManyToManyField(blank=True, help_text='Продукти, които потребителят е добавил в любими', related_name='favourited_by', to='products.product', verbose_name='Любими продукти')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Потребител',
                'verbose_name_plural': 'Потребители',
                'ordering': ['-date_joined'],
                'permissions': [('can_view_reports', 'Може да преглежда отчети'), ('can_manage_inventory', 'Може да управлява наличности'), ('can_manage_orders', 'Може да управлява всички поръчки')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
