# Generated by Django 6.0.1 on 2026-04-24 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Чакаща'), ('processing', 'Обработва се'), ('shipped', 'Изпратена'), ('delivered', 'Доставена'), ('cancelled', 'Отказана')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата на създаване')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата на обновяване')),
                ('guest_name', models.CharField(blank=True, max_length=100, verbose_name='Име (гост)')),
                ('guest_email', models.EmailField(blank=True, max_length=254, verbose_name='Имейл (гост)')),
                ('guest_phone', models.CharField(blank=True, max_length=15, verbose_name='Телефон (гост)')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Адрес за доставка')),
                ('notes', models.TextField(blank=True, verbose_name='Бележки към поръчката')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Обща сума')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Потребител')),
            ],
            options={
                'verbose_name': 'Поръчка',
                'verbose_name_plural': 'Поръчки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
