# Generated by Django 6.0.1 on 2026-03-18 12:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Име')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Имейл')),
                ('customer_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Телефонният номер трябва да съдържа между 9 и 20 символа: цифри, +, -, (), интервали.', regex='^[\\d\\s\\+\\-\\(\\)]{9,20}$')], verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('status', models.CharField(choices=[('pending', 'Чакащо'), ('processing', 'Обработва се'), ('completed', 'Завършено'), ('cancelled', 'Отказано')], default='pending', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Поръчка',
                'verbose_name_plural': 'Поръчки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена при поръчка')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Артикул в поръчка',
                'verbose_name_plural': 'Артикули в поръчки',
            },
        ),
    ]
