# Generated by Django 6.0.1 on 2026-03-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Поръчка', 'verbose_name_plural': 'Поръчки'},
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Бележки към поръчката'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, verbose_name='Адрес за доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата на създаване'),
        ),
        migrations.AlterField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Имейл (гост)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Име (гост)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Телефон (гост)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Чакаща'), ('processing', 'Обработва се'), ('shipped', 'Изпратена'), ('delivered', 'Доставена'), ('cancelled', 'Отказана')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата на обновяване'),
        ),
    ]
