# Generated by Django 6.0.1 on 2026-04-24 13:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Име на категорията')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създадено на')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Име на продукта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (€)')),
                ('product_type', models.CharField(choices=[('laptop', 'Ноутбук'), ('accessory', 'Аксесоар'), ('component', 'Компонент'), ('other', 'Други')], default='laptop', max_length=20, verbose_name='Тип на продукта')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Налично количество')),
                ('is_available', models.BooleanField(default=True, verbose_name='Наличен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създадено на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновено на')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Снимка')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Среден рейтинг')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='Брой отзиви')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Категория')),
                ('related_products', models.ManyToManyField(blank=True, to='products.product', verbose_name='Свързани продукти')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
                'ordering': ['-created_at'],
            },
        ),
    ]
